import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';

export default function DisclaimerPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1 py-16 sm:py-24">
        <section className="container max-w-4xl mx-auto">
          <div className="space-y-8 text-sm text-muted-foreground">
            <h1 className="font-headline text-3xl font-bold tracking-tighter sm:text-4xl text-foreground">
              Disclaimer
            </h1>
            <p>Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
            
            <div className="space-y-4">
              <h2 className="text-xl font-semibold text-foreground">1. No Financial Advice</h2>
              <p>The information provided by CFO Buddy ("we," "us," or "our") on our website and through our services is for informational purposes only. All financial analysis, forecasts, risk assessments, and other information generated by our AI are not to be considered as professional financial, investment, legal, or tax advice.</p>
              <p>You should not rely on the information provided as a substitute for professional advice from a qualified financial advisor, accountant, or legal professional. You should consult with your own professional advisors before making any financial decisions.</p>

              <h2 className="text-xl font-semibold text-foreground">2. Accuracy of Information</h2>
              <p>While we strive to provide accurate and up-to-date information, the analysis provided by our AI is based on the data you upload and the algorithms we use. We make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information generated by our service.</p>
              <p>The AI may produce errors, omissions, or inaccuracies. We are not responsible for any decisions made based on the information provided by our service.</p>

              <h2 className="text-xl font-semibold text-foreground">3. Limitation of Liability</h2>
              <p>Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of our site or services or reliance on any information provided. Your use of our services and your reliance on any information is solely at your own risk.</p>

              <h2 className="text-xl font-semibold text-foreground">4. Forward-Looking Statements</h2>
              <p>Our services may contain forecasts and other forward-looking statements that are based on assumptions and expectations. These statements are not guarantees of future performance and are subject to risks, uncertainties, and other factors that could cause actual results to differ materially from those expressed or implied by such statements.</p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
